FROM umihico/aws-lambda-selenium-python:latest

# Copy the Prep Lambda handler
COPY workspace_prep.py ${LAMBDA_TASK_ROOT}/workspace_prep.py

# Install required Python dependencies
RUN pip install --no-cache-dir \
    boto3 \
    selenium

# Set the Lambda handler entrypoint
CMD ["workspace_prep.handler"]
